name: atiss
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.21
  - numpy=1.19.1
  - networkx=2.5.1
  - pyrr=0.10.3
  - pyyaml=5.3.1
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.10.0
  - cudatoolkit=11.3
  - pillow=7.2.0
  - scipy=1.5.2
  - tqdm=4.50.2
  - trimesh=3.8.10
  - matplotlib=3.3.1
  - wxpython=4.0.7
  - pip:
    - git+https://github.com/angeloskath/simple-3dviz.git
    - git+https://github.com/idiap/fast-transformers.git
    - fastapi==0.104.1
    - uvicorn==0.24.0.post1
